/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lecture1Pckg;

/**
 *
 * @author zia
 */
public class PrePostIncrement extends javax.swing.JFrame {

    /**
     * Creates new form PrePostIncrement
     */
    public PrePostIncrement() {
        initComponents();
        
        
        
        jRadioButton_a_pre.setActionCommand("Pre");
        jRadioButton_b_pre.setActionCommand("Pre");
        jRadioButton_c_pre.setActionCommand("Pre");
        jRadioButton_d_pre.setActionCommand("Pre");
        jRadioButton_e_pre.setActionCommand("Pre");
        jRadioButton_f_pre.setActionCommand("Pre");
        jRadioButton_g_pre.setActionCommand("Pre");
        
        jRadioButton_a_post.setActionCommand("Post");
        jRadioButton_b_post.setActionCommand("Post");
        jRadioButton_c_post.setActionCommand("Post");
        jRadioButton_d_post.setActionCommand("Post");
        jRadioButton_e_post.setActionCommand("Post");
        jRadioButton_f_post.setActionCommand("Post");
        jRadioButton_g_post.setActionCommand("Post");
        
        jRadioButton_a_pre.setSelected(true);
        jRadioButton_b_pre.setSelected(true);
        jRadioButton_c_pre.setSelected(true);
        jRadioButton_d_pre.setSelected(true);
        jRadioButton_e_pre.setSelected(true);
        jRadioButton_f_pre.setSelected(true);
        jRadioButton_g_pre.setSelected(true);
        
        
        jRadioButton_a_inc.setActionCommand("++");
        jRadioButton_b_inc.setActionCommand("++");
        jRadioButton_c_inc.setActionCommand("++");
        jRadioButton_d_inc.setActionCommand("++");
        jRadioButton_e_inc.setActionCommand("++");
        jRadioButton_f_inc.setActionCommand("++");
        jRadioButton_g_inc.setActionCommand("++");
        
        jRadioButton_a_dec.setActionCommand("--");
        jRadioButton_b_dec.setActionCommand("--");
        jRadioButton_c_dec.setActionCommand("--");
        jRadioButton_d_dec.setActionCommand("--");
        jRadioButton_e_dec.setActionCommand("--");
        jRadioButton_f_dec.setActionCommand("--");
        jRadioButton_g_dec.setActionCommand("--");
        
        jRadioButton_a_inc.setSelected(true);
        jRadioButton_b_inc.setSelected(true);
        jRadioButton_c_inc.setSelected(true);
        jRadioButton_d_inc.setSelected(true);
        jRadioButton_e_inc.setSelected(true);
        jRadioButton_f_inc.setSelected(true);
        jRadioButton_g_inc.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrePostGrp_a = new javax.swing.ButtonGroup();
        PrePostGrp_b = new javax.swing.ButtonGroup();
        PrePostGrp_c = new javax.swing.ButtonGroup();
        PrePostGrp_d = new javax.swing.ButtonGroup();
        PrePostGrp_e = new javax.swing.ButtonGroup();
        PrePostGrp_f = new javax.swing.ButtonGroup();
        PrePostGrp_g = new javax.swing.ButtonGroup();
        IncDecGrp_a = new javax.swing.ButtonGroup();
        IncDecGrp_b = new javax.swing.ButtonGroup();
        IncDecGrp_c = new javax.swing.ButtonGroup();
        IncDecGrp_d = new javax.swing.ButtonGroup();
        IncDecGrp_e = new javax.swing.ButtonGroup();
        IncDecGrp_f = new javax.swing.ButtonGroup();
        IncDecGrp_g = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JText_a = new javax.swing.JTextField();
        JText_b = new javax.swing.JTextField();
        JText_c = new javax.swing.JTextField();
        JText_d = new javax.swing.JTextField();
        JText_e = new javax.swing.JTextField();
        JText_f = new javax.swing.JTextField();
        JText_g = new javax.swing.JTextField();
        DeclareValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DeclareValueMsg = new javax.swing.JLabel();
        jRadioButton_a_pre = new javax.swing.JRadioButton();
        jRadioButton_a_post = new javax.swing.JRadioButton();
        jRadioButton_b_pre = new javax.swing.JRadioButton();
        jRadioButton_b_post = new javax.swing.JRadioButton();
        jRadioButton_c_post = new javax.swing.JRadioButton();
        jRadioButton_c_pre = new javax.swing.JRadioButton();
        jRadioButton_d_pre = new javax.swing.JRadioButton();
        jRadioButton_d_post = new javax.swing.JRadioButton();
        jRadioButton_e_post = new javax.swing.JRadioButton();
        jRadioButton_e_pre = new javax.swing.JRadioButton();
        jRadioButton_f_pre = new javax.swing.JRadioButton();
        jRadioButton_f_post = new javax.swing.JRadioButton();
        jRadioButton_g_pre = new javax.swing.JRadioButton();
        jRadioButton_g_post = new javax.swing.JRadioButton();
        jRadioButton_a_inc = new javax.swing.JRadioButton();
        jRadioButton_a_dec = new javax.swing.JRadioButton();
        a_arg_b = new javax.swing.JComboBox<>();
        b_arg_c = new javax.swing.JComboBox<>();
        c_arg_d = new javax.swing.JComboBox<>();
        d_arg_e = new javax.swing.JComboBox<>();
        e_arg_f = new javax.swing.JComboBox<>();
        f_arg_g = new javax.swing.JComboBox<>();
        ExpresionText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton_b_inc = new javax.swing.JRadioButton();
        jRadioButton_b_dec = new javax.swing.JRadioButton();
        jRadioButton_c_inc = new javax.swing.JRadioButton();
        jRadioButton_c_dec = new javax.swing.JRadioButton();
        jRadioButton_d_dec = new javax.swing.JRadioButton();
        jRadioButton_d_inc = new javax.swing.JRadioButton();
        jRadioButton_e_inc = new javax.swing.JRadioButton();
        jRadioButton_e_dec = new javax.swing.JRadioButton();
        jRadioButton_f_inc = new javax.swing.JRadioButton();
        jRadioButton_f_dec = new javax.swing.JRadioButton();
        jRadioButton_g_dec = new javax.swing.JRadioButton();
        jRadioButton_g_inc = new javax.swing.JRadioButton();
        ResultCalc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pre Post Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(850, 373));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 351));

        JText_a.setEditable(false);
        JText_a.setBackground(new java.awt.Color(204, 204, 204));
        JText_a.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_a.setToolTipText("");

        JText_b.setEditable(false);
        JText_b.setBackground(new java.awt.Color(204, 204, 204));
        JText_b.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_b.setToolTipText("");

        JText_c.setEditable(false);
        JText_c.setBackground(new java.awt.Color(204, 204, 204));
        JText_c.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_c.setToolTipText("");

        JText_d.setEditable(false);
        JText_d.setBackground(new java.awt.Color(204, 204, 204));
        JText_d.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_d.setToolTipText("");

        JText_e.setEditable(false);
        JText_e.setBackground(new java.awt.Color(204, 204, 204));
        JText_e.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_e.setToolTipText("");

        JText_f.setEditable(false);
        JText_f.setBackground(new java.awt.Color(204, 204, 204));
        JText_f.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_f.setToolTipText("");

        JText_g.setEditable(false);
        JText_g.setBackground(new java.awt.Color(204, 204, 204));
        JText_g.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JText_g.setToolTipText("");

        DeclareValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DeclareValue.setText("0");
        DeclareValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DeclareValueKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Declare Value");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Variables");

        jLabel3.setText("a");

        jLabel4.setText("b");

        jLabel5.setText("c");

        jLabel6.setText("d");

        jLabel7.setText("e");

        jLabel8.setText("f");

        jLabel9.setText("g");

        DeclareValueMsg.setForeground(new java.awt.Color(255, 0, 0));

        PrePostGrp_a.add(jRadioButton_a_pre);
        jRadioButton_a_pre.setText("Pre");

        PrePostGrp_a.add(jRadioButton_a_post);
        jRadioButton_a_post.setText("Post");

        PrePostGrp_b.add(jRadioButton_b_pre);
        jRadioButton_b_pre.setText("Pre");

        PrePostGrp_b.add(jRadioButton_b_post);
        jRadioButton_b_post.setText("Post");

        PrePostGrp_c.add(jRadioButton_c_post);
        jRadioButton_c_post.setText("Post");

        PrePostGrp_c.add(jRadioButton_c_pre);
        jRadioButton_c_pre.setText("Pre");

        PrePostGrp_d.add(jRadioButton_d_pre);
        jRadioButton_d_pre.setText("Pre");

        PrePostGrp_d.add(jRadioButton_d_post);
        jRadioButton_d_post.setText("Post");

        PrePostGrp_e.add(jRadioButton_e_post);
        jRadioButton_e_post.setText("Post");

        PrePostGrp_e.add(jRadioButton_e_pre);
        jRadioButton_e_pre.setText("Pre");

        PrePostGrp_f.add(jRadioButton_f_pre);
        jRadioButton_f_pre.setText("Pre");

        PrePostGrp_f.add(jRadioButton_f_post);
        jRadioButton_f_post.setText("Post");

        PrePostGrp_g.add(jRadioButton_g_pre);
        jRadioButton_g_pre.setText("Pre");

        PrePostGrp_g.add(jRadioButton_g_post);
        jRadioButton_g_post.setText("Post");

        IncDecGrp_a.add(jRadioButton_a_inc);
        jRadioButton_a_inc.setText("++");

        IncDecGrp_a.add(jRadioButton_a_dec);
        jRadioButton_a_dec.setText("--");

        a_arg_b.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        b_arg_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        c_arg_d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        d_arg_e.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        e_arg_f.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        f_arg_g.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        ExpresionText.setEditable(false);
        ExpresionText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Expression");

        jButton1.setText("Get Expression");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IncDecGrp_b.add(jRadioButton_b_inc);
        jRadioButton_b_inc.setText("++");

        IncDecGrp_b.add(jRadioButton_b_dec);
        jRadioButton_b_dec.setText("--");

        IncDecGrp_c.add(jRadioButton_c_inc);
        jRadioButton_c_inc.setText("++");

        IncDecGrp_c.add(jRadioButton_c_dec);
        jRadioButton_c_dec.setText("--");

        IncDecGrp_d.add(jRadioButton_d_dec);
        jRadioButton_d_dec.setText("--");

        IncDecGrp_d.add(jRadioButton_d_inc);
        jRadioButton_d_inc.setText("++");

        IncDecGrp_e.add(jRadioButton_e_inc);
        jRadioButton_e_inc.setText("++");

        IncDecGrp_e.add(jRadioButton_e_dec);
        jRadioButton_e_dec.setText("--");

        IncDecGrp_f.add(jRadioButton_f_inc);
        jRadioButton_f_inc.setText("++");

        IncDecGrp_f.add(jRadioButton_f_dec);
        jRadioButton_f_dec.setText("--");

        IncDecGrp_g.add(jRadioButton_g_dec);
        jRadioButton_g_dec.setText("--");

        IncDecGrp_g.add(jRadioButton_g_inc);
        jRadioButton_g_inc.setText("++");

        ResultCalc.setEditable(false);
        ResultCalc.setMinimumSize(new java.awt.Dimension(20, 20));
        ResultCalc.setOpaque(false);

        jLabel11.setText("System Calculated Result");

        jButton2.setText("Get Result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(DeclareValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeclareValueMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResultCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JText_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a_arg_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton_a_pre)
                                    .addComponent(jRadioButton_a_post)
                                    .addComponent(jRadioButton_a_dec)
                                    .addComponent(jRadioButton_a_inc))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(JText_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton_b_pre)
                                            .addComponent(jRadioButton_b_post))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b_arg_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton_b_dec)
                                    .addComponent(jRadioButton_b_inc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(JText_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadioButton_c_pre)
                                            .addComponent(jRadioButton_c_post))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_arg_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton_c_dec)
                                    .addComponent(jRadioButton_c_inc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JText_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d_arg_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton_d_pre)
                                    .addComponent(jRadioButton_d_post)
                                    .addComponent(jRadioButton_d_dec)
                                    .addComponent(jRadioButton_d_inc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JText_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e_arg_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton_e_pre)
                                    .addComponent(jRadioButton_e_post)
                                    .addComponent(jRadioButton_e_dec)
                                    .addComponent(jRadioButton_e_inc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JText_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f_arg_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton_f_pre)
                                    .addComponent(jRadioButton_f_post)
                                    .addComponent(jRadioButton_f_dec)
                                    .addComponent(jRadioButton_f_inc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_g_dec)
                                    .addComponent(jRadioButton_g_inc)
                                    .addComponent(jRadioButton_g_pre)
                                    .addComponent(jRadioButton_g_post)
                                    .addComponent(jLabel9)
                                    .addComponent(JText_g, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ExpresionText))
                        .addGap(88, 88, 88))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JText_a, JText_b, JText_c, JText_d, JText_e, JText_f, JText_g, jRadioButton_a_post, jRadioButton_a_pre, jRadioButton_b_post, jRadioButton_b_pre, jRadioButton_c_post, jRadioButton_c_pre, jRadioButton_d_post, jRadioButton_d_pre, jRadioButton_e_post, jRadioButton_e_pre, jRadioButton_f_post, jRadioButton_f_pre, jRadioButton_g_post, jRadioButton_g_pre});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeclareValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DeclareValueMsg)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_arg_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_arg_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(f_arg_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JText_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_arg_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_arg_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_arg_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_a_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_a_post))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_b_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_b_post))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_g_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_g_post))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_c_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_c_post))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_d_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_d_post))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_e_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_e_post))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_f_pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_f_post)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_a_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_a_dec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_b_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_b_dec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_c_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_c_dec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_d_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_d_dec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_e_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_e_dec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_f_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_f_dec))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_g_inc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_g_dec)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpresionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ResultCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DeclareValue, DeclareValueMsg, jLabel1, jLabel2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeclareValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DeclareValueKeyTyped
        // TODO add your handling code here:
        try {
            
            int i = Integer.parseInt(DeclareValue.getText()); 
            DeclareValue.setText(String.valueOf(i));
            JText_a.setText(String.valueOf(i));
            JText_b.setText(String.valueOf(i));
            JText_c.setText(String.valueOf(i));
            JText_d.setText(String.valueOf(i));
            JText_e.setText(String.valueOf(i));
            JText_f.setText(String.valueOf(i));
            JText_g.setText(String.valueOf(i));
            DeclareValueMsg.setText("");
        } catch (NumberFormatException e) {
            DeclareValueMsg.setText("Invalid Number");
        }
    }//GEN-LAST:event_DeclareValueKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String VPrePost_a, VExp_a, VPrePost_b, VExp_b, VPrePost_c, VExp_c, VPrePost_d, VExp_d,
                VPrePost_e, VExp_e, VPrePost_f, VExp_f, VPrePost_g, VExp_g;
        
        VPrePost_a = PrePostGrp_a.getSelection().getActionCommand();
        
        if (VPrePost_a.toString() == "Pre"){
          VExp_a = IncDecGrp_a.getSelection().getActionCommand() + 'a';
        }
        else {
          VExp_a = 'a' + IncDecGrp_a.getSelection().getActionCommand();
        }
        
        VPrePost_b = PrePostGrp_b.getSelection().getActionCommand();
        
        if (VPrePost_b.toString() == "Pre"){
          VExp_b = IncDecGrp_b.getSelection().getActionCommand() + 'b';
        }
        else {
          VExp_b = 'b' + IncDecGrp_b.getSelection().getActionCommand();
        }
        
        VPrePost_c = PrePostGrp_c.getSelection().getActionCommand();
        
        if (VPrePost_c.toString() == "Pre"){
          VExp_c = IncDecGrp_c.getSelection().getActionCommand() + 'c';
        }
        else {
          VExp_c = 'c' + IncDecGrp_c.getSelection().getActionCommand();
        }
        
        VPrePost_d = PrePostGrp_d.getSelection().getActionCommand();
        
        if (VPrePost_d.toString() == "Pre"){
          VExp_d = IncDecGrp_d.getSelection().getActionCommand() + 'd';
        }
        else {
          VExp_d = 'd' + IncDecGrp_d.getSelection().getActionCommand();
        }
        
        
        ExpresionText.setText(VExp_a + ' ' + a_arg_b.getSelectedItem().toString());
        ExpresionText.setText( ExpresionText.getText() + ' '+ VExp_b + ' ' + b_arg_c.getSelectedItem().toString());
        ExpresionText.setText( ExpresionText.getText() + ' '+ VExp_c + ' ' + c_arg_d.getSelectedItem().toString());
        ExpresionText.setText( ExpresionText.getText() + ' '+ VExp_d + ' ' + d_arg_e.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int v_input_a, v_input_b;
        int v_result;
        String v_expression = "++v_input_a + v_input_b++";
        
        v_input_a = Integer.parseInt(JText_a.getText());
        v_input_b = Integer.parseInt(JText_b.getText());
        
        v_result = v_expression.hashCode();
        
        ResultCalc.setText(""+v_result);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrePostIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrePostIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrePostIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrePostIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrePostIncrement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeclareValue;
    private javax.swing.JLabel DeclareValueMsg;
    private javax.swing.JTextField ExpresionText;
    private javax.swing.ButtonGroup IncDecGrp_a;
    private javax.swing.ButtonGroup IncDecGrp_b;
    private javax.swing.ButtonGroup IncDecGrp_c;
    private javax.swing.ButtonGroup IncDecGrp_d;
    private javax.swing.ButtonGroup IncDecGrp_e;
    private javax.swing.ButtonGroup IncDecGrp_f;
    private javax.swing.ButtonGroup IncDecGrp_g;
    private javax.swing.JTextField JText_a;
    private javax.swing.JTextField JText_b;
    private javax.swing.JTextField JText_c;
    private javax.swing.JTextField JText_d;
    private javax.swing.JTextField JText_e;
    private javax.swing.JTextField JText_f;
    private javax.swing.JTextField JText_g;
    private javax.swing.ButtonGroup PrePostGrp_a;
    private javax.swing.ButtonGroup PrePostGrp_b;
    private javax.swing.ButtonGroup PrePostGrp_c;
    private javax.swing.ButtonGroup PrePostGrp_d;
    private javax.swing.ButtonGroup PrePostGrp_e;
    private javax.swing.ButtonGroup PrePostGrp_f;
    private javax.swing.ButtonGroup PrePostGrp_g;
    private javax.swing.JTextField ResultCalc;
    private javax.swing.JComboBox<String> a_arg_b;
    private javax.swing.JComboBox<String> b_arg_c;
    private javax.swing.JComboBox<String> c_arg_d;
    private javax.swing.JComboBox<String> d_arg_e;
    private javax.swing.JComboBox<String> e_arg_f;
    private javax.swing.JComboBox<String> f_arg_g;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_a_dec;
    private javax.swing.JRadioButton jRadioButton_a_inc;
    private javax.swing.JRadioButton jRadioButton_a_post;
    private javax.swing.JRadioButton jRadioButton_a_pre;
    private javax.swing.JRadioButton jRadioButton_b_dec;
    private javax.swing.JRadioButton jRadioButton_b_inc;
    private javax.swing.JRadioButton jRadioButton_b_post;
    private javax.swing.JRadioButton jRadioButton_b_pre;
    private javax.swing.JRadioButton jRadioButton_c_dec;
    private javax.swing.JRadioButton jRadioButton_c_inc;
    private javax.swing.JRadioButton jRadioButton_c_post;
    private javax.swing.JRadioButton jRadioButton_c_pre;
    private javax.swing.JRadioButton jRadioButton_d_dec;
    private javax.swing.JRadioButton jRadioButton_d_inc;
    private javax.swing.JRadioButton jRadioButton_d_post;
    private javax.swing.JRadioButton jRadioButton_d_pre;
    private javax.swing.JRadioButton jRadioButton_e_dec;
    private javax.swing.JRadioButton jRadioButton_e_inc;
    private javax.swing.JRadioButton jRadioButton_e_post;
    private javax.swing.JRadioButton jRadioButton_e_pre;
    private javax.swing.JRadioButton jRadioButton_f_dec;
    private javax.swing.JRadioButton jRadioButton_f_inc;
    private javax.swing.JRadioButton jRadioButton_f_post;
    private javax.swing.JRadioButton jRadioButton_f_pre;
    private javax.swing.JRadioButton jRadioButton_g_dec;
    private javax.swing.JRadioButton jRadioButton_g_inc;
    private javax.swing.JRadioButton jRadioButton_g_post;
    private javax.swing.JRadioButton jRadioButton_g_pre;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
